shell.run("wget https://raw.githubusercontent.com/nyan-ko/lua_funny/main/ore_mining.lua ore_mining.lua")
shell.run("wget https://raw.githubusercontent.com/nyan-ko/lua_funny/main/mining_utils.lua mining_utils.lua")
shell.run("wget https://raw.githubusercontent.com/nyan-ko/lua_funny/main/utils.lua utils.lua")
shell.run("wget https://raw.githubusercontent.com/nyan-ko/lua_funny/main/download.lua download.lua")
shell.run("wget https://raw.githubusercontent.com/nyan-ko/lua_funny/main/clean.lua clean.lua")
-- shell.run("wget ")
